// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: info/info.proto

package info

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for service information
type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_info_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_info_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_info_info_proto_rawDescGZIP(), []int{0}
}

// Response containing service information
type GetInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Core service information
	Info          *ServiceInformation `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_info_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_info_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_info_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetInfo() *ServiceInformation {
	if x != nil {
		return x.Info
	}
	return nil
}

// Information about the service
type ServiceInformation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service version
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Additional service details
	Details       map[string]string `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInformation) Reset() {
	*x = ServiceInformation{}
	mi := &file_info_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInformation) ProtoMessage() {}

func (x *ServiceInformation) ProtoReflect() protoreflect.Message {
	mi := &file_info_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInformation.ProtoReflect.Descriptor instead.
func (*ServiceInformation) Descriptor() ([]byte, []int) {
	return file_info_info_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceInformation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceInformation) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_info_info_proto protoreflect.FileDescriptor

const file_info_info_proto_rawDesc = "" +
	"\n" +
	"\x0finfo/info.proto\x12\x04info\"\x10\n" +
	"\x0eGetInfoRequest\"?\n" +
	"\x0fGetInfoResponse\x12,\n" +
	"\x04Info\x18\x01 \x01(\v2\x18.info.ServiceInformationR\x04Info\"\xab\x01\n" +
	"\x12ServiceInformation\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12?\n" +
	"\adetails\x18\x02 \x03(\v2%.info.ServiceInformation.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012E\n" +
	"\vInfoService\x126\n" +
	"\aGetInfo\x12\x14.info.GetInfoRequest\x1a\x15.info.GetInfoResponseB-Z+git.sonicoriginal.software/grpc-protos/infob\x06proto3"

var (
	file_info_info_proto_rawDescOnce sync.Once
	file_info_info_proto_rawDescData []byte
)

func file_info_info_proto_rawDescGZIP() []byte {
	file_info_info_proto_rawDescOnce.Do(func() {
		file_info_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_info_info_proto_rawDesc), len(file_info_info_proto_rawDesc)))
	})
	return file_info_info_proto_rawDescData
}

var file_info_info_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_info_info_proto_goTypes = []any{
	(*GetInfoRequest)(nil),     // 0: info.GetInfoRequest
	(*GetInfoResponse)(nil),    // 1: info.GetInfoResponse
	(*ServiceInformation)(nil), // 2: info.ServiceInformation
	nil,                        // 3: info.ServiceInformation.DetailsEntry
}
var file_info_info_proto_depIdxs = []int32{
	2, // 0: info.GetInfoResponse.Info:type_name -> info.ServiceInformation
	3, // 1: info.ServiceInformation.details:type_name -> info.ServiceInformation.DetailsEntry
	0, // 2: info.InfoService.GetInfo:input_type -> info.GetInfoRequest
	1, // 3: info.InfoService.GetInfo:output_type -> info.GetInfoResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_info_info_proto_init() }
func file_info_info_proto_init() {
	if File_info_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_info_info_proto_rawDesc), len(file_info_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_info_info_proto_goTypes,
		DependencyIndexes: file_info_info_proto_depIdxs,
		MessageInfos:      file_info_info_proto_msgTypes,
	}.Build()
	File_info_info_proto = out.File
	file_info_info_proto_goTypes = nil
	file_info_info_proto_depIdxs = nil
}
